name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22'
        
    - name: Install dependencies
      run: go mod download
      
    - name: Build application
      run: go build -o main ./cmd/main.go
      
    - name: Build Docker image
      run: |
        docker build -t arizidane/hotel-mawar-indah-availability-api:latest .
        
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Push Docker image
      run: |
        docker push arizidane/hotel-mawar-indah-availability-api:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: SSH to server and deploy
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull arizidane/hotel-mawar-indah-availability-api:latest
          docker stop my-container || true
          docker rm my-container || true
          docker run -d -p 8080:8080 --name my-container arizidane/hotel-mawar-indah-availability-api:latest
